# NOT CURRENTLY WORKING
name: build-and-test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: initial-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Start the server in the background using bun
      - name: Start Server
        run: bun src/index.ts &
        background: true

      # Wait for the server to be up and running
      - name: Wait for Server
        run: npx wait-on http://localhost:your_port
        timeout-minutes: 5

      # Run your tests
      - name: Run Tests
        run: npm test

      # Stop the background server (optional)
      - name: Stop Server
        run: pkill -f "bun src/index.ts" || true