# NOT CURRENTLY WORKING
name: build-and-test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: initial-tests
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      # - run: bun src/index.ts
      - run: bun test